### ISSUE TITLE
Undefined symbols for architecture arm64

### ISSUE THREAD

**Issue by joeshonm** [jiulongw/swift-unity#1]
After follow the updates provided in this guide I'm down to one error. Not sure what this means.

Other developers say it's a result of missing libraries, but I'm including all the recommended files. Maybe I'm missing something. I would greatly appreciate the help.

`Undefined symbols for architecture arm64:
  "_UnityStartWWWConnectionCustom", referenced from:
      TransportiPhone::DoRequest(core::basic_string<char, core::StringStorageDefault<char> > const&, unsigned long, UnityWebRequestMethod, core::basic_string<char, core::StringStorageDefault<char> > const&, bool, bool, HeaderHelper*, UploadHandler*, DownloadHandler*, ResponseHelper*, bool) in libiPhone-lib.a(TransportiPhone.o)
  "_UnitySendWWWConnection", referenced from:
      TransportiPhone::DoRequest(core::basic_string<char, core::StringStorageDefault<char> > const&, unsigned long, UnityWebRequestMethod, core::basic_string<char, core::StringStorageDefault<char> > const&, bool, bool, HeaderHelper*, UploadHandler*, DownloadHandler*, ResponseHelper*, bool) in libiPhone-lib.a(TransportiPhone.o)
  "_UnityBlockWWWConnectionUntilDone", referenced from:
      TransportiPhone::Finalize() in libiPhone-lib.a(TransportiPhone.o)
      TransportiPhone::PostRequest() in libiPhone-lib.a(TransportiPhone.o)
  "_UnityDestroyWWWConnection", referenced from:
      TransportiPhone::~TransportiPhone() in libiPhone-lib.a(TransportiPhone.o)
      TransportiPhone::Cleanup() in libiPhone-lib.a(TransportiPhone.o)
  "_UnityGetGLViewController", referenced from:
      -[AchievementWrapper showAchievementsUI] in libiPhone-lib.a(GameCenter.o)
      -[LeaderboardWrapper showLeaderboardUI:withTimeScope:] in libiPhone-lib.a(GameCenter.o)
  "_UnityShouldCancelWWW", referenced from:
      TransportiPhone::Abort() in libiPhone-lib.a(TransportiPhone.o)
      TransportiPhone::Finalize() in libiPhone-lib.a(TransportiPhone.o)
  "_UnityGetMetalBundle", referenced from:
      MetalBundleImpl() in libiPhone-lib.a(PluginInterfaceGraphicsMetal.o)
  "_UnityDocumentsDir", referenced from:
      systeminfo::GetPersistentDataPath() in libiPhone-lib.a(TrampolineGlue.o)
  "_UnityDeviceName", referenced from:
      systeminfo::GetDeviceName() in libiPhone-lib.a(TrampolineGlue.o)
  "_UnityDeviceModel", referenced from:
      systeminfo::GetDeviceModel() in libiPhone-lib.a(TrampolineGlue.o)
  "_UnityDeviceUniqueIdentifier", referenced from:
      systeminfo::GetDeviceUniqueIdentifier() in libiPhone-lib.a(TrampolineGlue.o)
  "_UnityDeviceCPUCount", referenced from:
      systeminfo::GetProcessorCount() in libiPhone-lib.a(TrampolineGlue.o)
  "LocationService::IsHeadingAvailable()", referenced from:
      UnityEngine::PlatformWrapper::GetSensorFlags() in libiPhone-lib.a(runtime_unityconnect.lump.o)
  "_OBJC_CLASS_$_UnityAppController", referenced from:
      objc-class-ref in AppDelegate.o
  "_UnityAdvertisingIdentifier", referenced from:
      AdsIdHandler::FetchAdsId() in libiPhone-lib.a(platformdependent_iphoneplayer.lump.o)
  "RegisterMonoModules()", referenced from:
      _unity_init in UnityUtils.o
  "_UnityCachesDir", referenced from:
      LocalFileSystemiPhone::GetUserAppCacheFolder() const in libiPhone-lib.a(runtime_virtualfilesystem.lump.o)
      systeminfo::GetTemporaryCachePath() in libiPhone-lib.a(TrampolineGlue.o)
  "_UnityLibraryDir", referenced from:
      LocalFileSystemiPhone::GetUserAppDataFolder() const in libiPhone-lib.a(runtime_virtualfilesystem.lump.o)
  "_UnityApplicationDir", referenced from:
      LocalFileSystemiPhone::GetApplicationPath() const in libiPhone-lib.a(runtime_virtualfilesystem.lump.o)
  "_UnitySystemLanguage", referenced from:
      iphone::GetSystemLanguage() in libiPhone-lib.a(iPhoneMisc.o)
  "_UnityDeviceIsStylusTouchSupported", referenced from:
      ____Z22IsStylusTouchSupportedv_block_invoke in libiPhone-lib.a(iPhoneInputImpl.o)
  "__ios91orNewer", referenced from:
      ____Z22IsStylusTouchSupportedv_block_invoke in libiPhone-lib.a(iPhoneInputImpl.o)
  "_UnityUpdateNoBackupFlag", referenced from:
      iphone::SetFileFlags(char const*, unsigned int, unsigned int) in libiPhone-lib.a(iPhoneMisc.o)
  "_UnityAdvertisingTrackingEnabled", referenced from:
      AdsIdHandler::FetchAdsId() in libiPhone-lib.a(platformdependent_iphoneplayer.lump.o)
  "_UnityDisplayManager_DisplayRenderingResolution", referenced from:
      _UnityDisplayManager_GetDisplayDeviceAt in libiPhone-lib.a(LibEntryPoint.o)
  "_il2cpp_no_exceptions", referenced from:
      ScriptingInvocation::Invoke(ScriptingExceptionPtr*, bool) in libiPhone-lib.a(runtime_scripting2.lump.o)
  "_UnityIsGyroAvailable", referenced from:
      IsGyroAvailable() in libiPhone-lib.a(LibEntryPoint.o)
  "_OBJC_CLASS_$_FIRApp", referenced from:
      objc-class-ref in AppDelegate.o
  "_UnityGetGLView", referenced from:
      IsMultiTouchEnabled() in libiPhone-lib.a(iPhoneInputImpl.o)
  "_UnitySystemVersion", referenced from:
      systeminfo::GetDeviceSystemVersion() in libiPhone-lib.a(TrampolineGlue.o)
  "_UnitySystemName", referenced from:
      systeminfo::GetDeviceSystemName() in libiPhone-lib.a(TrampolineGlue.o)
  "__ios90orNewer", referenced from:
      ____Z21IsForceTouchSupportedv_block_invoke in libiPhone-lib.a(iPhoneInputImpl.o)
  "RegisterFeatures()", referenced from:
      _unity_init in UnityUtils.o
  "UnityInitTrampoline()", referenced from:
      _unity_init in UnityUtils.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
 `

**Comment by jiulongw** [comment]
`_UnityStartWWWConnectionCustom` is defined in `Classes/Unity/WWWConnection.mm`.  Make sure your bridging header file is set properly and that `WWWConnection.mm` file is added to the build target, as shown in the screen shot below.

<img width="964" alt="screen shot 2017-10-03 at 11 04 56 am" src="https://user-images.githubusercontent.com/1650734/31141076-3ac8a7ac-a82b-11e7-8061-0397922e0977.png">

**Comment by DawidvanGraan** [comment]
@joeshonm Maybe try the steps listed in the issue: #2

**Comment by jplongo** [comment]
First thanks @jiulongw for your great example of integrating Unity 2017 build.
Everything work like a charm.

To prevent this issue I think you can add in your README :
- Check that all your Unity *.mm and *.cpp are in Target Membership.

That solve all my linker error...

**Comment by jiulongw** [comment]
@joeshonm Please try if this is fixed in latest master.  Adding files to Xcode project build target is fully automated now.

@jplongo Thanks!  I have changed to post build code to automatically add them into target membership so no need to worry about this issue any more. :)

**Comment by joeshonm** [comment]
@jiulongw and @DawidvanGraan and @jplongo Thanks for your help!

Yes, I needed to add all of the necessary .cpp and .mm files for the project to run. I greatly appreciate the help!
