### ISSUE TITLE
Xcode compilation errors for Unity 2017.2.0f3

### ISSUE THREAD

**Issue by Sander-Kornev** [jiulongw/swift-unity#10]
Probably it is connected to the latest version of Unity or whatever.
I use Unity 2017.2.0f3 + Xcode 9.0.1

At first I got following error while compiling DemoApp in Xcode
`UnityInitApplicationGraphics(UNITY_FORCE_DIRECT_RENDERING);`
../DemoApp/Unity/Classes/UnityAppController.mm:121:5: No matching function for call to 'UnityInitApplicationGraphics'

And as we can see in UnityInterface.h, 41 line function signature is without arguments
`void    UnityInitApplicationGraphics();`

So let's delete UNITY_FORCE_DIRECT_RENDERING argument and try.

After that I got following compilation  errors in MetalHelper.mm

line 67
../DemoApp/Unity/Classes/Unity/MetalHelper.mm:67:30: Array type '__strong MTLTextureRef [3]' is not assignable
http://prntscr.com/h1yzb6

line 274
../DemoApp/Unity/Classes/Unity/MetalHelper.mm:274:40: Assigning to 'MTLTextureRef' (aka 'id<MTLTexture>') from incompatible type '__strong MTLTextureRef [3]'
http://prntscr.com/h1yzhu

Attempt to comment these lines out leads to runtime crash 
-[MTLDebugRenderCommandEncoder setScissorRect:]:2566: failed assertion `(rect.y(150) + rect.height(1184))(1334) must be <= render pass height(1184)'

**Comment by Sander-Kornev** [comment]
I've got it, you excluded this file from copying because it has fix you mentioned in Readme about MTLTextureUsageRenderTarget.

So I've tried to remove MetalHelper.mm from excluding files and actually new copied file become 384 lines length versus 321 in old version. So it's no wander that it didn't work for me. Now everything compiles. And it seems they added MTLTextureUsageRenderTarget.

However I still has the same crash while rotating device to landscape mode.

**Comment by jiulongw** [comment]
Thanks @Sander-Kornev I'll find a way to support both 2017.1 and 2017.2...

As for the assertion failure you mentioned, have you tried to run without debugger attached?  For me seems like this error only happens when debugger attached.

**Comment by s5346** [comment]
thanks for @Sander-Kornev ,i have the same question, and i update the MetalHelper.mm for unity project build to ios project's MetalHelper.mm.
and like @jiulongw say, it not debug, device not connect Xcode, it won't crash.
thank @jiulongw

**Comment by jiulongw** [comment]
Fixed in 92289895c7bbba384557678ec5285779f4688ac5

**Comment by AbreuRodrigo** [comment]
Hey guys it seems like UnityInitApplicationGraphics(UNITY_FORCE_DIRECT_RENDERING); should have no parameters anymore, so in XCode just try changing it to UnityInitApplicationGraphics( );
