### ISSUE TITLE
DemoApp project crashes on start

### ISSUE THREAD

**Issue by UnityXCodeDeveloper** [jiulongw/swift-unity#101]
Facing crash issue on start up.

Steps :-
1. cloned project from 
https://github.com/jiulongw/swift-unity

2. Open project in Unity 2018.2.0f2

3 Build Xcode

4. Open DemoApp 
some how there were no classed and library folder so I manually copied those folders from unity exported xcode project to DemoApp project.

5. Set certificate and hit build button

I ended with an error of  "rsync: link_stat "/Users/AbcGame/Desktop/Unity" failed: No such file or directory (2)"

so I then checked "Run script only when installing" from Build phase then I was able to build.

After build when I run app in device I get white screen and then it crashed with following log.

2018-09-07 12:10:58.579514+0530 DemoApp[14273:3748744] [DYMTLInitPlatform] platform initialization successful
2018-09-07 12:10:58.807743+0530 DemoApp[14273:3748518] Built from '2018.2/staging' branch, Version '2018.2.0f2 (787658998520)', Build type 'Release', Scripting Backend 'il2cpp'
no boot config - using default values
 
(Filename:  Line: 135)

2018-09-07 12:10:58.817129+0530 DemoApp[14273:3748518] -> registered mono modules 0x10268e440
-> applicationDidFinishLaunching()
DemoApp was compiled with optimization - stepping may behave oddly; variables may not be available.

Please help......

**Comment by UnityXCodeDeveloper** [comment]
I managed to solve the problem.
Data folder was missing and some changes in splashscreen.mm file

**Comment by westk0r** [comment]
Hello! How did you fixed this problem?

**Comment by qiven** [comment]
Set it before you start：
[ufw setDataBundleId: "com.unity3d.framework"];
