### ISSUE TITLE
Can't release the unityappcontroller instance?

### ISSUE THREAD

**Issue by lawinko** [jiulongw/swift-unity#134]
Now I am integrating with native IOS. Everything is fine but Unity has a "Tap to native IOS" button and then I want to completely relaunch the Unity not to resume. Is it possible to release the instance of Unity and create a new instance again?

**Comment by WyattMufson** [comment]
Also interested in learning this

**Comment by WyattMufson** [comment]
@jiulongw ?

**Comment by ghost** [comment]
This is not possible in Unity iOS, even on Unity docs is covered this part. The best approach that you can take is to redirect to an empty scene when your app return to native swift.

**Comment by lawinko** [comment]
@linkalex3000  Thanks for the reply. I will close the issue.
