### ISSUE TITLE
Communicate from Unity to Swift

### ISSUE THREAD

**Issue by cobear25** [jiulongw/swift-unity#14]
@jiulongw  I see how you're communicating from swift to Unity with `UnityPostMessage()` but how do you send data/messages from a unity script back to the swift project?

**Comment by jplongo** [comment]
By following this answer on iOS-unity5 issue, I was able to communicate from Unity to iOS:

[https://github.com/blitzagency/ios-unity5/issues/16#issuecomment-247895934](ios-Unity5)

Here is what I did:
## Step 1

Add extern static in my QuitButton script and call this methods in my onClick Listener:

**[System.Runtime.InteropServices.DllImport("__Internal")]
	extern static public void quitUnity();**


```
public class QuitButton : MonoBehaviour
{
	public Button yourButton;
	[System.Runtime.InteropServices.DllImport("__Internal")]
	extern static public void quitUnity();

	void Start()
	{
		Button btn = yourButton.GetComponent<Button>();
		btn.onClick.AddListener(TaskOnClick);
	}

	void TaskOnClick()
	{
		#if UNITY_IOS && !UNITY_EDITOR
		quitUnity();
		#endif
	}
}
```

## Step 2

Add Objective C++ method in your UnityUtils.mm file with the same name in your button script

`extern "C" void quitUnity() {
    NSLog(@"Stop Button tapped from Unity content");
}`

With this to things, you will be able to print Log message to Xcode Console when button is tapped.
Now I'm trying to find how I can call StopUnity() from quitUnity() method. Just need to call AppDelegate, but don't know how for the moment.

Hope it will help you to embed Unity->iOS communication...

**Comment by jiulongw** [comment]
Thanks @jplongo !  Added to demo.

**Comment by davidbarile** [comment]
Thank you. This was most useful.  Question: when upgrading my app to 64bit for the latest Android requirements, this line of code breaks the build. 

[System.Runtime.InteropServices.DllImport("__Internal")]

 Any suggestions?
