### ISSUE TITLE
Unity with Vuforia integration

### ISSUE THREAD

**Issue by torok-zoltan** [jiulongw/swift-unity#15]
I followed the guide and it works for unity without vuforia, but it fails if vuforia is integrated in the unity project.
Any idea what I need to change to make it work with vuforia ?

**Comment by jiulongw** [comment]
Could you elaborate more about the error details?  Was it build time error or run time error?  Any message / stack traces?

**Comment by jiulongw** [comment]
Close due to inactivity.
