### ISSUE TITLE
Compiling the Demo gives me "entry point (_main) undefined. for architecture arm64"

### ISSUE THREAD

**Issue by rjcristy** [jiulongw/swift-unity#17]
I'm at 

https://github.com/jiulongw/swift-unity#how-to-run-the-demo

However it's giving me an error 

    ld: entry point (_main) undefined. for architecture arm64

**Comment by jiulongw** [comment]
I think you opened the Xcode project generated by Unity, right?  You should open the [this project](https://github.com/jiulongw/swift-unity/tree/master/demo/xcode), not the generated one.

**Comment by rjcristy** [comment]
Ok thank you very much for your fast response!
