### ISSUE TITLE
iOS Swift project can't open after Unity Build 

### ISSUE THREAD

**Issue by mosluce** [jiulongw/swift-unity#19]
Version
- Xcode : 9.1 (9B55)
- Unity : 2017.2.0f3

<img width="532" alt="2017-11-24 4 23 11" src="https://user-images.githubusercontent.com/1487051/33201558-03283ff6-d134-11e7-8069-035a78760302.png">

**Comment by jiulongw** [comment]
Would you mind send me your xcodeproj to take a look?  Also, do you see any errors in Unity console output when building iOS output?

**Comment by mosluce** [comment]
@jiulongw 

OK, I send my xcodeproj for u.
[Demo.xcodeproj.zip](https://github.com/jiulongw/swift-unity/files/1504407/Demo.xcodeproj.zip)

and no error when building iOS output in Unity Console.

<img width="1029" alt="2017-11-27 8 51 39" src="https://user-images.githubusercontent.com/1487051/33246525-505854c8-d350-11e7-976e-d7e86859a222.png">

**Comment by jiulongw** [comment]
$ xcodebuild -project Demo.xcodeproj/
2017-11-26 20:31:13.101 xcodebuild[85746:12344773] Error Domain=NSCocoaErrorDomain Code=3840 "Unexpected character / at line 1" UserInfo={NSDebugDescription=Unexpected character / at line 1, kCFPropertyListOldStyleParsingError=Error Domain=NSCocoaErrorDomain Code=3840 "**Unexpected character '0x9ed8' at line 2100**" UserInfo={NSDebugDescription=Unexpected character '0x9ed8' at line 2100}}
xcodebuild: error: Unable to read project 'Demo.xcodeproj'.
	Reason: Project /Users/jiulongw/Downloads/Demo.xcodeproj cannot be opened because the project file cannot be parsed.

I guess there is some encoding issue when Unity saves pbxproj file.  You can temporary change these Chinese characters to ascii characters and then change them back in Xcode.
```
				ORGANIZATIONNAME = 默司;
```

**Comment by mosluce** [comment]
Cool, I change 

> ORGANIZATIONNAME = 默司;

to

> ORGANIZATIONNAME = "默司";

It's solved.  
Thank you for your help.
