### ISSUE TITLE
IOException: Win32 IO returned ERROR_ALREADY_EXISTS, when build again

### ISSUE THREAD

**Issue by mosluce** [jiulongw/swift-unity#20]
OS : macOS 10.13.2 beta

<img width="538" alt="2017-11-30 9 20 29" src="https://user-images.githubusercontent.com/1487051/33408161-e8deabc8-d5af-11e7-82d7-5d7ddf1e2696.png">

**Comment by jiulongw** [comment]
To work around this issue, choose "Replace" when building Unity project.
