### ISSUE TITLE
Failed build Demo

### ISSUE THREAD

**Issue by hai2014bk** [jiulongw/swift-unity#26]
When i build, i got this error, any help please, it's urgent

> Syncing code from ...
rsync: link_stat "/Classes/." failed: No such file or directory (2)
rsync error: some files could not be transferred (code 23) at /BuildRoot/Library/Caches/com.apple.xbs/Sources/rsync/rsync-51/rsync/main.c(996) [sender=2.6.9]
rsync: link_stat "/Libraries/." failed: No such file or directory (2)
rsync error: some files could not be transferred (code 23) at /BuildRoot/Library/Caches/com.apple.xbs/Sources/rsync/rsync-51/rsync/main.c(996) [sender=2.6.9]
Command /bin/sh failed with exit code 23

Please help me
Thank you

**Comment by jiulongw** [comment]
Try to quit and reopen Xcode.  It seems values `Exports.xcconfig` are not picked up properly.

**Comment by hai2014bk** [comment]
@jiulongw thanks for your response, but i've try quit and reopen a tons of time :(
and it's seem like i didn't get Exports.xcconfig ?

**Comment by jiulongw** [comment]
What is the output of Unity console after build?  Is there any error? (Make sure your build target is iOS otherwise it won't work.  Default is desktop application)

**Comment by hai2014bk** [comment]
@jiulongw thanks for your response, after i build ios Unity of your demo, then i ran demoApp by Xcode, and i gave me 200 error, such as like this 
`"_gEnableStylusTouch", referenced from:
      RegisterFeatures() in RegisterFeatures.o`

**Comment by jiulongw** [comment]
@hai2014bk did you run it in emulator?  Unity app does not support x86 iOS emulator.  You have to run it in an actual device.

**Comment by hai2014bk** [comment]
@jiulongw hi, the demo have ran, but when i change to another Unity (i kept all of your project like Xcode... but change my unity project), then i builded, i got this
`DemoApp/Unity/Classes/Native/Bulk_System_0.cpp:29987:75: No member named 'Mono' in namespace 'il2cpp::icalls::System'`

**Comment by hai2014bk** [comment]
now Mono error has gone, but i face another, that is my custom lib has't been found, although it have been linked ?? help me pls @jiulongw

**Comment by jiulongw** [comment]
How did you link your custom lib?  Did you link in Unity or Xcode?

**Comment by jiulongw** [comment]
Closed since there is no response.  Feel free to re-open if needed.
