### ISSUE TITLE
How does it work?

### ISSUE THREAD

**Issue by revolter** [jiulongw/swift-unity#28]
How does it automatically detect the Unity build folder?

**Comment by jiulongw** [comment]
The Unity post build script write the Unity build folder into `Exports.xcconfig`.  It is then picked up by Xcode to copy all necessary files.

**Comment by revolter** [comment]
And `XcodeProjectRoot` and `XcodeProjectName` must be updated by the user, right?

**Comment by jiulongw** [comment]
Yes!
