### ISSUE TITLE
Undefined symbols for architecture arm64

### ISSUE THREAD

**Issue by IzikAlgrisi** [jiulongw/swift-unity#29]
Hello, I followed your instructions multiple times but i cant managed to build in xcode 9 project.
Xcode 9.
Unity 2017.2.0f3 (Finally try with sample unity placeholder code)
Unity Build for devices - universal with IL2CPP.

I still get the error (no code in swift, and no code in unity for test after many times).

Undefined symbols for architecture arm64:
"_MTAudioProcessingTapGetSourceAudio", referenced from:
AVFoundationVideoPlayback::PlayerPriv::ProcessAudioTap(opaqueMTAudioProcessingTap const*, long, unsigned int, AudioBufferList*, long*, unsigned int*) in libiPhone-lib.a(AVFoundationVideoPlayback.o)
"_MTAudioProcessingTapCreate", referenced from:
-[AVFoundationMediaLoader ConfigureAudioOutput] in libiPhone-lib.a(AVFoundationVideoPlayback.o)
"_MTAudioProcessingTapGetStorage", referenced from:
-[AVFoundationMediaLoader ConfigureAudioOutput] in libiPhone-lib.a(AVFoundationVideoPlayback.o)
AVFoundationVideoPlayback::PlayerPriv::PrepareAudioTap(opaqueMTAudioProcessingTap const*, long, AudioStreamBasicDescription const*) in libiPhone-lib.a(AVFoundationVideoPlayback.o)
AVFoundationVideoPlayback::PlayerPriv::ProcessAudioTap(opaqueMTAudioProcessingTap const*, long, unsigned int, AudioBufferList*, long*, unsigned int*) in libiPhone-lib.a(AVFoundationVideoPlayback.o)
AVFoundationVideoPlayback::PlayerPriv::FinalizeAudioTap(opaqueMTAudioProcessingTap const*) in libiPhone-lib.a(AVFoundationVideoPlayback.o)
-[AVFoundationMediaLoader StopOutput] in libiPhone-lib.a(AVFoundationVideoPlayback.o)
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

Thank you for help
Itzik

**Comment by jiulongw** [comment]
Google it and you should find these missing symbols are defined in MediaToolbox.  Try to add `-framework MediaToolbox` to `OTHER_LDFLAGS`.

**Comment by IzikAlgrisi** [comment]
Oh, sorry i tried once and didnt work. and is work.
Thanks a lot. 
I have a new question, In my native xcode project, we used with some packages and pod file look:

>pod 'AFNetworking/NSURLSession'
pod 'GoogleMaps'
pod 'SearchTextField'

> and  our conf file look 
> 
> ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES = YES
> FRAMEWORK_SEARCH_PATHS = $(inherited) "$PODS_CONFIGURATION_BUILD_DIR/AFNetworking" "$PODS_CONFIGURATION_BUILD_DIR/SearchTextField" "${PODS_ROOT}/GoogleMaps/Base/Frameworks" "${PODS_ROOT}/GoogleMaps/Maps/Frameworks"
> GCC_PREPROCESSOR_DEFINITIONS = $(inherited) COCOAPODS=1
> HEADER_SEARCH_PATHS = $(inherited) "${PODS_ROOT}/Headers/Public" "${PODS_ROOT}/Headers/Public/GoogleMaps"
> LD_RUNPATH_SEARCH_PATHS = $(inherited) '@executable_path/Frameworks' '@loader_path/Frameworks'
> OTHER_CFLAGS = $(inherited) -iquote "$PODS_CONFIGURATION_BUILD_DIR/AFNetworking/AFNetworking.framework/Headers" -iquote "$PODS_CONFIGURATION_BUILD_DIR/SearchTextField/SearchTextField.framework/Headers" -isystem "${PODS_ROOT}/Headers/Public" -isystem "${PODS_ROOT}/Headers/Public/GoogleMaps"
> OTHER_LDFLAGS = $(inherited) -ObjC -l"c++" -l"z" -framework "AFNetworking" -framework "Accelerate" -framework "CoreData" -framework "CoreGraphics" -framework "CoreLocation" -framework "CoreText" -framework "GLKit" -framework "GoogleMaps" -framework "GoogleMapsBase" -framework "GoogleMapsCore" -framework "ImageIO" -framework "OpenGLES" -framework "QuartzCore" -framework "SearchTextField" -framework "SystemConfiguration" -framework "UIKit"
> OTHER_SWIFT_FLAGS = $(inherited) "-D" "COCOAPODS"
> PODS_BUILD_DIR = $BUILD_DIR
> PODS_CONFIGURATION_BUILD_DIR = $PODS_BUILD_DIR/$(CONFIGURATION)$(EFFECTIVE_PLATFORM_NAME)
> PODS_PODFILE_DIR_PATH = ${SRCROOT}/.
> PODS_ROOT = ${SRCROOT}/Pods
> 

If i merge your configuration file with our conf i get error:

> codegen/il2cpp-codegen.h' file not found


Thank a lot. you very help.

**Comment by jiulongw** [comment]
Could you elaborate more about how you merge these two configuration files?  Xcode only take one configuration file.  Could you post the merged file to gist and post a link here?

**Comment by IzikAlgrisi** [comment]
Just copy on each other.
Here is the Unity.xcconfig file

> #include "Exports.xcconfig"
> 
> UNITY_SCRIPTING_BACKEND = il2cpp;
> GCC_PREFIX_HEADER = $(PRODUCT_NAME)/Unity/Classes/Prefix.pch;
> 
> HEADER_SEARCH_PATHS = $(inherited) "$(PRODUCT_NAME)/Unity/Classes" "$(PRODUCT_NAME)/Unity/Classes/Unity" "$(PRODUCT_NAME)/Unity/Classes/Native" "$(PRODUCT_NAME)/Unity/Libraries" "$(PRODUCT_NAME)/Unity/Libraries/libil2cpp/include" ${PODS_HEADER_PATHS};
> 
> LIBRARY_SEARCH_PATHS = $(inherited) "$(PRODUCT_NAME)/Unity/Libraries" "$(PRODUCT_NAME)/Unity/Libraries/libil2cpp/include" ${PODS_LIBRARY_PATHS};
> 
> // If using .net 4.0 in Unity, append -DNET_4_0 to OTHER_CFLAGS
> OTHER_CFLAGS = $(inherited) -DINIT_SCRIPTING_BACKEND=1 -fno-strict-overflow -DRUNTIME_IL2CPP=1;
> 
> OTHER_LDFLAGS = $(inherited) -weak-lSystem -weak_framework CoreMotion -weak_framework GameKit -weak_framework iAd -framework AVFoundation -framework AudioToolbox -framework CFNetwork -framework CoreGraphics -framework CoreLocation -framework CoreMedia -framework CoreVideo -framework Foundation -framework MediaPlayer -framework MediaToolbox -framework Metal -framework OpenAL -framework OpenGLES -framework QuartzCore -framework SystemConfiguration -framework UIKit -liconv.2 -liPhone-lib -lil2cpp ${PODS_LIBRARIES};
> 
> SWIFT_OBJC_BRIDGING_HEADER = $(PRODUCT_NAME)/Unity/Bridging-Header.h;
> SWIFT_PRECOMPILE_BRIDGING_HEADER = YES;
> 
> 
> ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES = YES
> FRAMEWORK_SEARCH_PATHS = $(inherited) "$PODS_CONFIGURATION_BUILD_DIR/AFNetworking" "$PODS_CONFIGURATION_BUILD_DIR/SearchTextField" "${PODS_ROOT}/GoogleMaps/Base/Frameworks" "${PODS_ROOT}/GoogleMaps/Maps/Frameworks"
> GCC_PREPROCESSOR_DEFINITIONS = $(inherited) COCOAPODS=1
> HEADER_SEARCH_PATHS = $(inherited) "${PODS_ROOT}/Headers/Public" "${PODS_ROOT}/Headers/Public/GoogleMaps"
> LD_RUNPATH_SEARCH_PATHS = $(inherited) '@executable_path/Frameworks' '@loader_path/Frameworks'
> OTHER_CFLAGS = $(inherited) -iquote "$PODS_CONFIGURATION_BUILD_DIR/AFNetworking/AFNetworking.framework/Headers" -iquote "$PODS_CONFIGURATION_BUILD_DIR/SearchTextField/SearchTextField.framework/Headers" -isystem "${PODS_ROOT}/Headers/Public" -isystem "${PODS_ROOT}/Headers/Public/GoogleMaps"
> OTHER_LDFLAGS = $(inherited) -ObjC -l"c++" -l"z" -framework "AFNetworking" -framework "Accelerate" -framework "CoreData" -framework "CoreGraphics" -framework "CoreLocation" -framework "CoreText" -framework "GLKit" -framework "GoogleMaps" -framework "GoogleMapsBase" -framework "GoogleMapsCore" -framework "ImageIO" -framework "OpenGLES" -framework "QuartzCore" -framework "SearchTextField" -framework "SystemConfiguration" -framework "UIKit"
> OTHER_SWIFT_FLAGS = $(inherited) "-D" "COCOAPODS"
> PODS_BUILD_DIR = $BUILD_DIR
> PODS_CONFIGURATION_BUILD_DIR = $PODS_BUILD_DIR/$(CONFIGURATION)$(EFFECTIVE_PLATFORM_NAME)
> PODS_PODFILE_DIR_PATH = ${SRCROOT}/.
> PODS_ROOT = ${SRCROOT}/Pods
>

**Comment by jiulongw** [comment]
Xcode's `.config` file uses a very simple parser and always override same name variables defined in same file.  So, your second `OTHER_LDFLAGS` completely overwrites first one.  The `$(inherited)` expands to definition from previous level, not from previous definition in this file.

You have to manually merge them into one variable.

**Comment by jiulongw** [comment]
Feel free to re-open this if you still have problems.

**Comment by IzikAlgrisi** [comment]
Thank you so match.
I tried and work fine.
I had some mistake.
Itzik

**Comment by Janardhanrao** [comment]
@IzikAlgrisi 
sry for posing in closed issue 

`
Undefined` symbols for architecture arm64:
  "Geo::GetiOSAppDocumentsDir()", referenced from:
      Geo::PathUtils::GetSandboxDataPath() in libiPhone-lib.a(GeoPathUtils.o)
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
`

I am getting above error have any idea ?

Thnx in advance
