### ISSUE TITLE
Xcode compile error when using .Net 4.6 backend in Unity

### ISSUE THREAD

**Issue by IDobrinescu** [jiulongw/swift-unity#31]
After i (successfully) build my Unity project, the demo project fails to compile:

/Users/ionutdobrinescu/Development/UnityIntegration/V2/iOSProject/DemoApp/Unity/Classes/Native/Bulk_System.Configuration_0.cpp:25861:85: error: no member named 'Configuration' in namespace 'il2cpp::icalls::System'
        return ((InternalConfigurationHost_get_bundled_app_config_m1191888808_ftn)System::Configuration::System::Configuration::InternalConfigurationHost::get_bundled_app_config) ();

I have some external frameworks that i use and i tried to link them but this doesn't seem to be the problem.

![screen shot 2017-12-20 at 18 45 29](https://user-images.githubusercontent.com/22762014/34218176-2764e2d4-e5b6-11e7-948d-df07bce7919d.png)

Do you have any ideea how to solve this?

**Comment by jiulongw** [comment]
This is by design.  The Unity output (after applying the post build script) is not meant to be built by Xcode directly (that's why it's recommended to be dropped to `/tmp`).  Instead, you should open the companion Swift Xcode project, which will copy the necessary files from Unity output and build the iOS app.

**Comment by IDobrinescu** [comment]
This error doesn't appear in the Unity output project, but in the demo iOS app

**Comment by jiulongw** [comment]
This looks weird: `System::Configuration::System::Configuration`.

Which Unity / Xcode version do you use?

In Unity, which .net framework version did you use?

When building Unity, did you choose "Append" or "Replace"?

My gut feeling is the il2cpp files are messed around in the `Native` folder.  Try to create a clean unity build.  If not, I'd be happy to take a look at your project to repro it (if you don't mind).

**Comment by jiulongw** [comment]
I deleted original comment regarding building unity project directly... It was for another issue.  I posted in the wrong thread.

**Comment by IDobrinescu** [comment]
Ok, after some more testing i found out that using .Net 4.6 seems to cause this problem. I tested it using Unity 2017.3.f02 and Unity 2017.3.f03 with the same results. Unfortunately my Unity project uses .Net 4.6 and it would be really hard to go back to 3.5. Is there a way to solve this problem?

**Comment by jiulongw** [comment]
Yes.  There is a [comment][1] in `Unity.xcconfig` which reads:

> // If using .net 4.0 in Unity, append -DNET_4_0 to OTHER_CFLAGS

[1]: https://github.com/jiulongw/swift-unity/blob/db8afa30484240267e031c772136f83095a60f25/demo/xcode/DemoApp/Unity/Unity.xcconfig#L10

**Comment by jiulongw** [comment]
If vanilla Unity project can be built but Swift project throws errors.  Usually it is caused by different compiler / linker flags...

**Comment by jiulongw** [comment]
Feel free to re-open this issue if you still have problems.
