### ISSUE TITLE
Build project failed

### ISSUE THREAD

**Issue by KarinaFernandez** [jiulongw/swift-unity#37]
Hi @jiulongw ! First of all, thanks for creating this guide! 
I have been trying to follow all the guide steps but without success. When is time to build I get some errors like: 

> Undefined symbols for architecture arm64:
>   "_UnityGetMetalDrawableCommandQueue", referenced from:
>       MetalContext::PrepareCommandBufferIfNeeded() in libiPhone-lib.a(MetalContext.o)
>   "_UnityDeviceCPUCount", referenced from:
>       systeminfo::GetProcessorCount() in libiPhone-lib.a(TrampolineGlue.o)

I´m running it on a device and not in a simulator.

##
The steps that I did are:
1. Create a Unity project and build to iOS.
2. Copy the [script](https://github.com/jiulongw/swift-unity/blob/master/XcodePostBuild.cs) in the Assets folder of the Unity project and change **the path of the Xcode project that Unity created** (Is this okay? Or should be the path of the new project mentioned in the 4th step?).
3. Open de Xcode project that Unity created and build.
4. Create a new project and add the [Unity folder](https://github.com/jiulongw/swift-unity/tree/master/demo/xcode/DemoApp/Unity) that you give and add the .mm files to the target.
5. Add the ´.gitignore´file with the given lines.
6. Select Unity as project configuration file.
7. Add the run scripts in the target.
8. Build and run.
##

I know that could sound repetitive, but I´m not sure if understand all the steps of your guide (especially the first one, I don´t understand which project you start. 
> Copy entire Unity folder to the root of your Swift project and add it to Xcode source tree. Make sure all the .mm files are added to correct build target.).

Please let me know if I missing something or any of that steps that I´m doing are not necessary.
Thanks in advance! 

![screen shot 2018-01-19 at 12 17 17](https://user-images.githubusercontent.com/11321277/35158953-71604284-fd17-11e7-95da-dab3e65e2a8e.png)

**Comment by JasonPan** [comment]
It looks like it could be an issue with Metal.

Try going into your Unity Build Settings -> Player settings -> Other Settings and

    turn off Auto Graphics API,
    delete 'Metal' from the Graphics API list.

Hope this helps!

**Comment by KarinaFernandez** [comment]
Thank you so much @JasonPan ! My project still not working, but that solved the given issue!!!
