### ISSUE TITLE
I have a Crash when download the last release from the repo

### ISSUE THREAD

**Issue by gmoral** [jiulongw/swift-unity#41]
Im using Unity 2017.3.1f1 and XCode 9.2 and I have a crash when I run on device. Any idea?

best

2018-02-09 17:19:25.063517 DemoApp[219:4872] [DYMTLInitPlatform] platform initialization successful
2018-02-09 17:19:25.612060 DemoApp[219:4699] -> registered mono modules 0x101247520
-> applicationDidFinishLaunching()
2018-02-09 17:19:25.735239 DemoApp[219:4699] Metal GPU Frame Capture Enabled
2018-02-09 17:19:25.736423 DemoApp[219:4699] Metal API Validation Enabled
2018-02-09 17:19:26.099599 DemoApp[219:4699] Uncaught exception: NSInvalidArgumentException: Storyboard (<UIStoryboard: 0x17027b8c0>) doesn't contain a view controller with identifier 'unitySplashStoryboard'
(
	0   CoreFoundation                      0x00000001860761d8 <redacted> + 148
	1   libobjc.A.dylib                     0x0000000184ab055c objc_exception_throw + 56
	2   UIKit                               0x000000018c68a130 <redacted> + 0
	3   DemoApp                             0x00000001007df6f4 _Z16ShowSplashScreenP8UIWindow + 332
	4   DemoApp                             0x00000001007e0d40 -[UnityAppController(ViewHandling) createUI] + 1600
	5   DemoApp                             0x00000001000ee9e8 -[UnityAppController application:didFinishLaunchingWithOptions:] + 1196
	6   DemoApp                             0x00000001008009c0 _T07DemoApp0B8DelegateC11applicationSbSo13UIApplicationC_s10DictionaryVySC0E16LaunchOptionsKeyVypGSg022didFinishLaunchingWithH0tF + 480
	7   DemoApp                             0x0000000100801004 _T07DemoApp0B8DelegateC11applicationSbSo13UIApplicationC_s10DictionaryVySC0E16LaunchOptionsKeyVypGSg022didFinishLaunchingWithH0tFTo + 216
	8   UIKit                               0x000000018bf43100 <redacted> + 400
	9   UIKit                               0x000000018c153858 <redacted> + 3524
	10  UIKit                               0x000000018c1595c8 <redacted> + 1656
	11  UIKit                               0x000000018c16de60 <redacted> + 48
	12  UIKit                               0x000000018c1565ac <redacted> + 168
	13  FrontBoardServices                  0x0000000187c1d8bc <redacted> + 36
	14  FrontBoardServices                  0x0000000187c1d728 <redacted> + 176
	15  FrontBoardServices                  0x0000000187c1dad0 <redacted> + 56
	16  CoreFoundation                      0x0000000186024278 <redacted> + 24
	17  CoreFoundation                      0x0000000186023bc0 <redacted> + 524
	18  CoreFoundation                      0x00000001860217c0 <redacted> + 804
	19  CoreFoundation                      0x0000000185f50048 CFRunLoopRunSpecific + 444
	20  UIKit                               0x000000018bf3c2b0 <redacted> + 608
	21  UIKit                               0x000000018bf37034 UIApplicationMain + 208
	22  DemoApp                             0x0000000100801e0c main + 76
	23  libdyld.dylib                       0x0000000184f345b8 <redacted> + 4
)
2018-02-09 17:19:26.107848 DemoApp[219:4699] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: 'Storyboard (<UIStoryboard: 0x17027b8c0>) doesn't contain a view controller with identifier 'unitySplashStoryboard''
*** First throw call stack:
(0x1860761c0 0x184ab055c 0x18c68a130 0x1007df6f4 0x1007e0d40 0x1000ee9e8 0x1008009c0 0x100801004 0x18bf43100 0x18c153858 0x18c1595c8 0x18c16de60 0x18c1565ac 0x187c1d8bc 0x187c1d728 0x187c1dad0 0x186024278 0x186023bc0 0x1860217c0 0x185f50048 0x18bf3c2b0 0x18bf37034 0x100801e0c 0x184f345b8)
libc++abi.dylib: terminating with uncaught exception of type NSException

**Comment by RogueHogue** [comment]
Have you tried to define a viewcontroller with an ID of 'unitySplashStoryboard'? Because there is no reference at all to an ID like that in my project, and I used the demo.

**Comment by jiulongw** [comment]
In addition to @RogueHogue 's reply... I haven't try 2017.3.1f1 yet.  Will see if there's any breaking changes from 2017.3.0f1 and update this thread later.

**Comment by jx2359** [comment]
I managed to sidestep this issue by changing the LaunchScreen.storyboard filename to something else, e.g. LaunchScreen1.storyboard

this is because of a section of a code from SplashScreen.mm which causes the crash, and I cannot edit the file as Unity will revert to the original code:

`
    bool hasStoryboard = [[NSBundle mainBundle] pathForResource: @"LaunchScreen" ofType: @"storyboardc"] != nullptr;

    if (hasStoryboard)
    {
        UIStoryboard *storyboard = [UIStoryboard storyboardWithName: @"LaunchScreen" bundle: [NSBundle mainBundle]];
        _controller = [storyboard instantiateViewControllerWithIdentifier: @"unitySplashStoryboard"];
    }
    else
        _controller = [[SplashScreenController alloc] init];

    [_controller create: window];
    [window makeKeyAndVisible];
`

**Comment by gmoral** [comment]
I fixed the issue. I did this changed too on file XcodePostbuild.cs  

private static void PatchUnityNativeCode(string pathToBuiltProject)
    {
        EditMainMM(Path.Combine(pathToBuiltProject, "Classes/main.mm"));
        EditUnityAppControllerH(Path.Combine(pathToBuiltProject, "Classes/UnityAppController.h"));
        EditUnityAppControllerMM(Path.Combine(pathToBuiltProject, "Classes/UnityAppController.mm"));

        if (Application.unityVersion == "2017.1.1f1")
        {
            EditMetalHelperMM(Path.Combine(pathToBuiltProject, "Classes/Unity/MetalHelper.mm"));
		} else {
            EditSplashScreenMM(Path.Combine(pathToBuiltProject, "Classes/UI/SplashScreen.mm"));
        }
    }

Because Im using Unity 2017.3.1f1. Let me know if this change its ok.

Thanks guys for the info.

**Comment by jiulongw** [comment]
@jx2359 Yes Unity will revert your changes because it is generated by build process and not supposed to be manually changed.

I have pushed [the change](https://github.com/jiulongw/swift-unity/commit/ebaa882b9a64e383ab4f12c4bf8a0c44f7fa2a03) that fixes the issue.  Please pull latest master and see if that fixed your issue.  Thanks!

**Comment by jiulongw** [comment]
@gmoral Thanks for posting your solution!  The splash screen patch was applied to `2017.3.0f3` so better to include `2017.3.1f3` there instead of the `else` clause of `2017.1.1f1`.  I have pushed the changes so if you can pull latest master it should fix the crash issue.

**Comment by gmoral** [comment]
Awesome. Thanks guys!!!

**Comment by jiulongw** [comment]
Sorry I may made a mistake there. The version number is 2017.3.1f1 or 2017.3.1f3?...

**Comment by gmoral** [comment]
The version is 2017.3.1f1

![screen shot 2018-02-19 at 3 02 59 pm](https://user-images.githubusercontent.com/805764/36391633-1cffe05a-1586-11e8-875e-789e4fc3e123.png)

**Comment by jiulongw** [comment]
Thanks @gmoral .  [That](https://github.com/jiulongw/swift-unity/commit/93785f0f18879994f4fbefeb6ea5fc128bff101e) should fix it.  Weird Unity version numbers...

**Comment by gmoral** [comment]
Yep, you are right. Anyway now its working perfect. Thanks.

**Comment by gmoral** [comment]
Hi guys!! How can load an scene and set the NATIVE_BRIDGE. The idea is load an scene from an assetBundle an have the comunication with iOS. I don't know if I can create an istance of NATIVE_BRIDGE an set in the new scene and still can send message to IOS and receive message from IOS. Any idea?

Thanks in advance.

**Comment by jiulongw** [comment]
After loading the scene, you can create a new game object, name it `NATIVE_BRIDGE`, and attach the [`NativeBridge` script](https://github.com/jiulongw/swift-unity/blob/master/demo/unity/Assets/Scripts/NativeBridge.cs) to that game object.  Once that's done, communication between Unity and iOS should be working.  To make sure timing is correct, you can send a message from Unity to iOS so iOS would know when the communicate channel is established.

**Comment by gmoral** [comment]
Thanks Jiulongw. I will try that.

**Comment by larryPlayabl** [comment]
I'm seeing this problem again in 2017.4.10, FYI.
