### ISSUE TITLE
App Name was compiled with optimization - stepping may behave oddly; variables may not be available.

### ISSUE THREAD

**Issue by houssi2** [jiulongw/swift-unity#42]
When i run the project i get this error : 

App Name was compiled with optimization - stepping may behave oddly; variables may not be available.

<img width="561" alt="screen shot 2018-02-20 at 18 19 59" src="https://user-images.githubusercontent.com/10501113/36438636-cab650aa-166a-11e8-91f3-ecb8fd3c2fd7.png">

**Comment by jiulongw** [comment]
I don't think this is an error.  Did you see any problem running the app?  Maybe this is not the root cause.

**Comment by megaserfer** [comment]
I had the same. Just add this in Run Script.

```
echo "Syncing data from $UNITY_IOS_EXPORT_PATH..."
rm -rf "$TARGET_BUILD_DIR/$PRODUCT_NAME.app/Data"
cp -Rf "$UNITY_IOS_EXPORT_PATH/Data" "$TARGET_BUILD_DIR/$PRODUCT_NAME.app/Data"

```

$UNITY_IOS_EXPORT_PATH - is the path to unity export

**Comment by jiulongw** [comment]
Close due to inactivity.  Feel free to re-open if needed.
