### ISSUE TITLE
ios build error

### ISSUE THREAD

**Issue by CaduHammer** [jiulongw/swift-unity#43]
您好,

我们照着您的教学操作下，在ios的build成过程中出现错误如图 想请问应该是哪里的步骤出错了呢?

谢谢
<img width="1071" alt="2" src="https://user-images.githubusercontent.com/36691971/36469029-ccb33cae-1720-11e8-982a-f67dff494323.png">

**Comment by jiulongw** [comment]
你好！Unity目前还不支持x86_64架构的iOS模拟器，而Xcode的iOS模拟器似乎只有x86_64的。所以现在Unity的iOS app只能在真机上跑。你把run target改成iPhone/iPad应该就可以了。

**Comment by jiulongw** [comment]
Closing this issue since I believe it is the root cause. Feel free to re-open if you still have issue.
