### ISSUE TITLE
splash screen error

### ISSUE THREAD

**Issue by nikkigrace** [jiulongw/swift-unity#46]
Simply compiling the existing version gives me this:

Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: 'Storyboard (<UIStoryboard: 0x1c067bd00>) doesn't contain a view controller with identifier 'unitySplashStoryboard''

**Comment by jiulongw** [comment]
Hello @nikkigrace this is a known issue fixed yesterday.  Could you try pull latest master?

If you're sure you're using latest version, please tell me more about Unity/Xcode versions.

**Comment by nikkigrace** [comment]
Holy crap! Thank you so kindly for getting back to me so fast, my client needs this in by end of day and this is driving me crazy.

I pulled the code today so I'm not sure why that would be the case. 

xCode 9.2 / Unity 2017.3.0p2 / MacOS 10.13.2

**Comment by jiulongw** [comment]
hmm, I know the issue...  To quickly work around this issue, change unity version number [here](https://github.com/jiulongw/swift-unity/blob/master/XcodePostBuild.cs#L267).  Simply change `f` to `p` should be good enough.

I didn't know version p exists... Is it some internal version of Unity?

**Comment by nikkigrace** [comment]
You are fantastic. Do you have some sort of PayPal I can donate to if this works?

**Comment by nikkigrace** [comment]
You're literally saving my company's butt today. :P

**Comment by jiulongw** [comment]
Sure if you wish 😃   Paypal: jiulongw@live.com

**Comment by nikkigrace** [comment]
Okay, that built successfully! And ran fine. :3 Now I'm going to try to do this with my own.

**Comment by nikkigrace** [comment]
Hmm, so in simply copying over my project to yours, using the script you provided, I'm now getting an 'appdelegate.h' problem. That's probably because the project file is Swift. Is this something to do with the bridge? I'm so sorry to keep bugging you.

**Comment by nikkigrace** [comment]
Yup. Certainly stuck on this. No other project file will allow me to write over that content and compile. Every time I get an appdelegate.h issue.

**Comment by jiulongw** [comment]
I think you should copy necessary files from demo xcode project into your project, set the correct configurations in your xcode project setting, and let the build script pick up unity stuff into your project.  This is how I helped some people setup their environment.

**Comment by jiulongw** [comment]
Did you follow this? https://github.com/jiulongw/swift-unity#how-to-use-it-in-other-projects

**Comment by nikkigrace** [comment]
Yeah, absolutely. I'll give it another go from scratch and let you know. Thanks again for all your help. What a nightmare, I've been up since 8:30 just trying to get these two projects to merge. >.<

**Comment by jiulongw** [comment]
Good luck :) The tricky part is if you have pod file and when it comes with xcconfig files, you have to manually merge them...  Let me know where I can help.

**Comment by nikkigrace** [comment]
Alright, I do have a pod file. I have followed your instructions from scratch and still end up with the AppDelegate.h issue. What about the xconfig files may I have to fix?

**Comment by jiulongw** [comment]
Do you have detailed error message?

For merging xcconfigs, there are some instructions [here](https://github.com/jiulongw/swift-unity/blob/master/demo/xcode/DemoApp/Unity/Unity.xcconfig#L18).

**Comment by nikkigrace** [comment]
The cocoa pods are actually within my original xCode project, not the Unity project.

**Comment by nikkigrace** [comment]
/Users/---/Desktop/demo/xcode/WinnerApp/Unity/Libraries/Plugins/iOS/MyUnityAppController.mm:9:9: 'AppDelegate.h' file not found

**Comment by jiulongw** [comment]
Should be a pretty simple fix... Usually this means the include path is missing because you're using cocoapod's configuration.  You need to edit cocoapod xcconfig file to include necessary information from Unity.xcconfig, more specifically, the `HEADER_SEARCH_PATHS` for this particular error.  But you need to include all other variables defined in Unity.xcconfig as well.

**Comment by nikkigrace** [comment]
adding these causes this error:

/Users/nikki/Desktop/demo/xcode/Pods/<built-in>:1:10: '/Users/nikki/Desktop/demo/xcode/Pods/Pods_-----App/Unity/Classes/Prefix.pch' file not found

**Comment by jiulongw** [comment]
GCC_PREFIX_HEADER = $(PRODUCT_NAME)/Unity/Classes/Prefix.pch;

be careful if you see same variable appears more than once in the same xcconfig file.  Last one completely overrides previous ones.  Even if you use `$(inherited)`, which only work for different levels, not same file.

**Comment by nikkigrace** [comment]
removing pods from the project made this script simply work like a dream! thank you so much, sir, and I'll make sure I hit your PayPal up, you've saved me a lot of time. :)

**Comment by jiulongw** [comment]
I'm closing this issue.  Let me know if you need anything else from me.  I do think merging with pod file configuration should work.

**Comment by James-Coleman** [comment]
The original issue of this thread appeared for me when I tried to use the beta version of Unity.
Obviously using beta software is at the developers risk, but adding ` || Application.unityVersion.StartsWith("2018.1.0b")` to [here](https://github.com/jiulongw/swift-unity/blob/master/XcodePostBuild.cs#L267) solved the issue for me.
