### ISSUE TITLE
ARKit Classes do not build

### ISSUE THREAD

**Issue by bilalpakeermohamed** [jiulongw/swift-unity#49]
Hi jiulongw,

After adding ARKIT_USES_FACETRACKING=1 to the OTHER_CFLAGS, I am getting the following error. Could you please have a look and let me know what the issue is?
![screen shot 2018-02-26 at 12 14 03](https://user-images.githubusercontent.com/19821714/36683421-766cda64-1b15-11e8-9c66-3d9dbc879925.png)

**Comment by jiulongw** [comment]
`-DARKIT_USES_FACETRACKING=1`, prefix with `-D`

**Comment by bilalpakeermohamed** [comment]
Thanks for the reply. Prefixing with -D does not solve the error. I tried -ARKIT_USES_FACETRACKING=1 and that seems to fix the error with 'Controls reaches end of non-void function for ARSessionNative.mm'

The next error is 'Control reached end of non-void function for Prefix.pch' which I was able to fix by adding -USE_IL2CPP_PCH=1 to the OTHER_CFLAGS.

But after that I get the error message 'Control reached end of non-void function for UIKit.h' that I have supplied the screenshot for above.

Could you please have a look and let me know?

**Comment by jiulongw** [comment]
Which line did this error happen?  The error message does not make any sense if you don't include the context...

**Comment by jiulongw** [comment]
Close due to inactivity.  Feel free to re-open if needed.
