### ISSUE TITLE
The type or namespace name 'Xcode' does not exist in the namespace 'UnityEditor.iOS'

### ISSUE THREAD

**Issue by makslevental** [jiulongw/swift-unity#5]
![screen shot 2017-10-09 at 5 24 50 pm](https://user-images.githubusercontent.com/5657668/31359197-f8e57716-ad16-11e7-918e-85ece3c3015f.png)

**Comment by jiulongw** [comment]
Hi @makslevental , thanks for your PR.  However, you're seeing this error because you need to put the post build script into `Editor` folder.  It is Unity convention that only scripts under `Editor` folder will get editor context and are excluded in player.

**Comment by makslevental** [comment]
@jiulongw thanks (although with the two line guard i think it might be a useful addition anyway).
