### ISSUE TITLE
UI API called from the background thread

### ISSUE THREAD

**Issue by etiennepinchon** [jiulongw/swift-unity#50]
Hi! 

Really amazing work! Works perfectly, except I get a warning during launch from the UnityAppController.h: "UI API called from the background thread: -[UIApplication delegate] must be used from main thread only" 

<img width="1251" alt="screen shot 2018-03-02 at 16 38 59" src="https://user-images.githubusercontent.com/20617726/36907204-51ab4cda-1e38-11e8-87b8-e181d33c359b.png">

Any idea how we could fix this?

Best

**Comment by jiulongw** [comment]
This is a Unity issue and according to Unity, will be fixed in Unity 2018.1.

https://issuetracker.unity3d.com/issues/ios11-api-called-on-a-background-thread-uiapplication-delegate-unitycurrentorientation-on-launch-in-an-empty-project

**Comment by etiennepinchon** [comment]
Oh great! Thank you!

**Comment by WyattMufson** [comment]
@jiulongw this still happens in 2019.1.14f1 - the screen goes white when `startUnity` is called and I get the purple main thread warning. UI interaction also appears to be disabled

**Comment by sandeepkiks** [comment]
@WyattMufson Did you managed to solve the issue, I am too trying on 2019.1.xx version but giving the same mesage `UI API called from the background thread`

**Comment by pjcau** [comment]
I see the same issue also on the release LTS 2018.4.14f1.
