### ISSUE TITLE
Use of undeclared type 'UnityAppController'

### ISSUE THREAD

**Issue by gohaneri** [jiulongw/swift-unity#51]
Hi man, after following your tutorial i get this errore when i try to build xCode:
Use of undeclared type 'UnityAppController' in AppDelegate.
What i've done wrong? :D
Unity build successfully, the Unity.xcconfig is created correctly..

**Comment by jiulongw** [comment]
Usually this means the header search path is not configured correctly.  Do you have cocoapods libraries?

**Comment by gohaneri** [comment]
Yep, i've a cocoapods libraries :D

**Comment by jiulongw** [comment]
Hmm seems like this is a very common situation and I will try to put some extra steps in README.  Basically if you have cocoapods, you're using cocoapods' configuration (xcconfig) which means the Unity.xcconfig is not used at all.  You need to merge important variables in Unity.xcconfig into the cocoapods configuration file *manually* (as far as I know, there may be better ways but I'm not Xcode expert).

**Comment by jiulongw** [comment]
Close due to inactivity.  Feel free to re-open if needed.
