### ISSUE TITLE
-[UIApplication delegate] must be used from main thread only

### ISSUE THREAD

**Issue by baksha97** [jiulongw/swift-unity#52]
I typically receive this purple error when I'm not calling UI changes in the DispatchQueue.main.async. I am not sure if the UnityAppController contains changes to the UI without the main.async? I see spikes in the cpu when the application starts and ends.

**Comment by jiulongw** [comment]
This is a Unity bug and will be fixed in version 2018...

See #50

**Comment by WyattMufson** [comment]
This issue still persists in the newest version of Unity

**Comment by shmiftari** [comment]
This issue still persists in the newest version of Unity
