### ISSUE TITLE
Instructions for how to add a trigger button from Unity to Trigger an action in the ViewController.

### ISSUE THREAD

**Issue by juang97** [jiulongw/swift-unity#53]
Currently, the notification observer is not being triggered although I have added the configuration to the NativeBridge.cs, rebuilt, and reinstalled my application. I can see the scripts have defined my method in Xcode, but it's not triggering the observer.

**Comment by jiulongw** [comment]
Could you add more details (like source code)?

From Unity to ViewController, all you need is an `extern "C"` function somewhere in your Xcode project, import it in Unity via `DllImport`, and call it directly in Unity script.

**Comment by jiulongw** [comment]
Close due to inactivity.  Feel free to re-open if needed.
