### ISSUE TITLE
Vuforia Image Tracking works in build but not Swift-Unity project

### ISSUE THREAD

**Issue by mayntos** [jiulongw/swift-unity#54]
We created a Unity-Vuforia build and works as intended w/ image tracking. 
Turned off Auto-Graphics API and removed Metal. However incorporating it using Swift-Unity causes an issue where the image tracking no longer works.

**Comment by timnlupo** [comment]
Had a similar issue, how did you resolve?

**Comment by jiulongw** [comment]
See #48 .  For now you might need to add Data folder in Xcode project.
