### ISSUE TITLE
Classes and Libraries Folders sometimes don't copy to Xcode project?

### ISSUE THREAD

**Issue by timnlupo** [jiulongw/swift-unity#55]
Sometimes when I build the Unity project, the _Classes_ and _Libraries_ folders do not copy over to the Xcode project. Everything else builds appropriately, but when I look in the physical [Xcode_Proj]/Unity folder there are no _Classes_ or _Libraries_ folders. They are also highlighted red in Xcode (missing)? Any potentisl reason why or fix?
Xcode 9.2 and Unity 2017.3.1f1, using the default Demo unity project.

**Comment by jiulongw** [comment]
This is expected.  The `Classes` and `Libraries` are copied only when Xcode project is being built (as part of the pre-build script).
