### ISSUE TITLE
Crash on startup (Xcode 9.2 , Unity2017)

### ISSUE THREAD

**Issue by oenama** [jiulongw/swift-unity#57]
<img width="998" alt="screen shot 2018-03-10 at 1 30 00 pm" src="https://user-images.githubusercontent.com/11976534/37241763-4ae90254-2467-11e8-9fc8-697beaf33731.png">

<img width="645" alt="screen shot 2018-03-10 at 2 00 41 pm" src="https://user-images.githubusercontent.com/11976534/37242047-76681ace-246b-11e8-9bf1-5cd7b991a6fd.png">

I'm trying to update my project , now using Unity2017 , Xcode 9.2. 
I've been following so many solutions around. nothing worked. 

I've checked this too :
https://github.com/blitzagency/ios-unity5/issues/52

Still can't figure it out. any ideas how to make it work 
(unity with Vuforia plugin)

any ideas how to fix this? thanks

**Comment by jiulongw** [comment]
You need to turn off Metal API for Vuforia.  See https://github.com/jiulongw/swift-unity/issues/34#issuecomment-357414737

**Comment by oenama** [comment]
@jiulongw 
thank you. it worked. 
but now I'm facing a problem, the view is upside down and  camera does not detect any object. 
I did run the unity iOS build alone before integrate it with my native iOS app, camera detect objects just fin. I did search and implement everything right. 
 
<img width="875" alt="screen shot 2018-03-24 at 11 36 50 am" src="https://user-images.githubusercontent.com/11976534/37862595-5ec92866-2f58-11e8-87f0-ff676c50cd64.png">

any ideas why camera does not detect any object when I integrate it with my native iOS App? 
thank you.

**Comment by oenama** [comment]
thank you I fixed it , it was issue with copying raw file which has Vuforia file,
for anyone who face this issue here's how I fixed it:
go to Build Phases -> Copy Bundle Resources, click the + sign, then click Add Other... and then select folder Vuforia located in **ProjectRootPath**/Data/Raw/ .(if the file does not appear in the list you can drag and drop it to the list and copy references).
