### ISSUE TITLE
 Showing Recent Issues Command /bin/sh failed with exit code 23

### ISSUE THREAD

**Issue by NallapatiMalleswari** [jiulongw/swift-unity#60]
![screen shot 2018-03-28 at 12 16 46 pm](https://user-images.githubusercontent.com/31246172/38013218-fa20f614-3281-11e8-8229-8640e8e7eeb4.png)

**Comment by jiulongw** [comment]
`Exports.xcconfig` not found... Did you build Unity project using iOS platform?

**Comment by jiulongw** [comment]
Close due to inactivity.  Feel free to re-open if needed.

**Comment by mc0ps** [comment]
Please help me with this issue!
