### ISSUE TITLE
crash on startup

### ISSUE THREAD

**Issue by mickeyevers77** [jiulongw/swift-unity#61]
I am having an issue when I try to run the demo. I always hat this error
<img width="989" alt="schermafbeelding 2018-03-30 om 00 14 58" src="https://user-images.githubusercontent.com/27244314/38116272-a6c3217a-33af-11e8-9dbe-ba3904372384.png">
<img width="493" alt="schermafbeelding 2018-03-30 om 00 17 05" src="https://user-images.githubusercontent.com/27244314/38116282-b32ea970-33af-11e8-89fb-05befe1565ee.png">
can you please help?

**Comment by jiulongw** [comment]
What is the Xcode / Unity version?

**Comment by mickeyevers77** [comment]
Xcode = Version 9.2 
Unity = Version 2017.3.1f1

**Comment by jiulongw** [comment]
It should work out of the box without any code change.  But looks like error is same with this (pretty old) issue.

https://github.com/jiulongw/swift-unity/issues/7

**Comment by mickeyevers77** [comment]
Thanks this was the problem, Data wasn't properly added to the project, thanks!

**Comment by sashakid** [comment]
And how to add Data properly?
