### ISSUE TITLE
valueForUndefinedKey

### ISSUE THREAD

**Issue by mickeyevers77** [jiulongw/swift-unity#62]
When I run my application, i get a valueForUndefinedKey error.
this is the full error
<img width="837" alt="schermafbeelding 2018-04-01 om 16 49 14" src="https://user-images.githubusercontent.com/27244314/38174373-bc6fd71a-35cc-11e8-8ae1-32bbb804f511.png">
<img width="856" alt="schermafbeelding 2018-04-01 om 16 48 42" src="https://user-images.githubusercontent.com/27244314/38174374-bc94e244-35cc-11e8-8e8c-63a000f115ee.png">

I am using cocoapods, but this shouldn't give me this error, anny help?

**Comment by mickeyevers77** [comment]
this is my appDelegate
<img width="534" alt="schermafbeelding 2018-04-01 om 17 35 40" src="https://user-images.githubusercontent.com/27244314/38174788-227ab556-35d3-11e8-9f8f-7f309f605408.png">
<img width="791" alt="schermafbeelding 2018-04-01 om 17 35 11" src="https://user-images.githubusercontent.com/27244314/38174789-22944476-35d3-11e8-9893-aab35b1d4966.png">

**Comment by djbe** [comment]
Ignore this, issue belongs in https://github.com/appwise-labs/AppwiseCore 😄
