### ISSUE TITLE
ProjectName-swift.h file has some error

### ISSUE THREAD

**Issue by Gamshan** [jiulongw/swift-unity#65]
I used unity inside of my native ios application. i already used facebook login packages inside my app it is work fine. but i integrate with unity by follow this code. **ProjectName-swift.h** has some error that module not found. I can fix in xcode and can run. but i can't build archive. When i build it is always give error on  ProjectName-swift.h
<img width="1280" alt="issue" src="https://user-images.githubusercontent.com/15510044/38614191-ddcc0de0-3da9-11e8-8ba6-1159930b4132.png">

**Comment by jiulongw** [comment]
Where is `FBSDKLoginButtonDelegate` defined?  Could you also post the header file search path of your current project?

You might need to add 3rd party header file path to `Unity.xcconfig` otherwise they are not imported properly.

**Comment by jiulongw** [comment]
Something like this:
https://github.com/jiulongw/swift-unity/blob/master/demo/xcode/DemoApp/Unity/Unity.xcconfig#L6

You need to add FB sdk header path to that variable.

**Comment by Gamshan** [comment]
Yes i fix the issue to add ` #import <FBSDKLoginKit/FBSDKLoginKit.h>` inside **Prefix.pch** file
