### ISSUE TITLE
Quit unity engine

### ISSUE THREAD

**Issue by Gamshan** [jiulongw/swift-unity#66]
I start the unity when i tap a button from a view controller. when i quit from unity i call `stopUnity()` but unity is still running in background. i load unity again from another view controller i call `startUnity()`  method. but the previous unity scene is visible.

My issue is how to completely stop the unity engine and start again. that means kill unity and start again

**Comment by jiulongw** [comment]
Currently there is no better solution other than mentioned in #25.
