### ISSUE TITLE
Xcode 9 - 2017.2.0f2 - Crash on Unity launch

### ISSUE THREAD

**Issue by joeshonm** [jiulongw/swift-unity#7]
I'm attempting to blend in a Unity-Vuforia project into an existing Swift project. So far everything builds, but as soon as I run the startUnity command the initialization only gets so far before crashing.

Here is the end of the console log:

-> applicationDidBecomeActive()
GfxDevice: creating device client; threaded=1
Initializing Metal device caps: Apple A10 GPU
Initialize engine version: 2017.2.0f2 (472de62575d5)
excaliburNYC was compiled with optimization - stepping may behave oddly; variables may not be available.
(lldb)

Thread Error:

0x105c61f44 <+20>: ldrb w8, [x19, #0x109]
Thread 1: EXC_BAD_ACCESS (code=1, address=0x109)

At the top of the thread error is says il2cpp::vm::Class::Init: and I have traced it back to this function below.

UnityInitApplicationGraphics();

Any help would be appreciated. Thank you.

**Comment by joeshonm** [comment]
I'm closing this issue. This happens when the Data folder is not being imported correctly for the application.

**Comment by ahmedAlmasri** [comment]
@joeshonm  how to solve this issue ??

**Comment by sashakid** [comment]
You've linked two issues on each other but there is no any information about how to fix it, only that Data wasn't added properly :-)
