### ISSUE TITLE
setDepthClipMode error

### ISSUE THREAD

**Issue by quotetoxic** [jiulongw/swift-unity#84]
[MTLDebugRenderCommandEncoder setDepthClipMode:]:2502: failed assertion `-[MTLDebugRenderCommandEncoder setDepthClipMode:] is only supported on MTLFeatureSet_iOS_GPUFamily2_v1 and later' - getting this error when trying to run the project on iOS device. What could be wrong?

**Comment by PrashantKT** [comment]
Are you getting this while attaching debugger ?

**Comment by quotetoxic** [comment]
It happens right after Initialize engine version when the app starts on the device

**Comment by PrashantKT** [comment]
did you added Data folder from unity to your ios project  if any ?

**Comment by quotetoxic** [comment]
I'm trying to run DemoApp provided as example, should i manually add Data folder from Unity build folder?

**Comment by wangjianpeng** [comment]
I had meet this problem also, but after i detach my phone from  debugger, the app works well.
Could you tell me the reason about this problem?

**Comment by chanyut** [comment]
I found the same problem. I thought the clue is that MTLDebugRenderCommandEncoder was called only while debugging. So after detached the device, the problem gone.
