### ISSUE TITLE
Apple Mach-O Linker (ld) Error Group

### ISSUE THREAD

**Issue by quotetoxic** [jiulongw/swift-unity#85]
Getting errors as on the picture + 180 more... What's wrong?
<img width="323" alt="screen shot 2018-06-15 at 14 50 45" src="https://user-images.githubusercontent.com/23323091/41468832-8c20dc5c-70ab-11e8-8db9-9bb34afc9132.png">

**Comment by PrashantKT** [comment]
Make sure you have added framework, and your frameworks is  also available at location (check for shortcuts )

**Comment by quotetoxic** [comment]
It is physically there... Could it be the issue with Vuforia?
