### ISSUE TITLE
Unity 2018.1.6f1 not compatible

### ISSUE THREAD

**Issue by AliSferea** [jiulongw/swift-unity#88]
Hi, first of all thanks for the amazing tutorial, it works like a charm. 

Recently I run into a problem with Unity+Vuforia and the new iOS version 11.4.

I had my unity project integrated on my xcode project. But in this new version of iOS, when I run my Unity Activity I got a black screen. I already investigate about the issue, and it is a problem with vuforia, wich I can solve updating Unity to its 2018.1.6f1 version but I'm not capable to make this tutorial work with that version of Unity.

Any idea of why this tutorial might no be working.

Thanks in regards. Sorry for my english.

**Comment by setoelkahfi** [comment]
Have you try to build your project with Xcode 9.2?

**Comment by melvinrudolph** [comment]
Hey same problem here !
Tutorial doesn't work with Unity 2018.
The problem with downgrading to Xcode 9.2 is that some of my Cocoapods aren't working with 9.2 anymore.
Is there any way to make this tutorial work with Xcode 9.4 and Unity 2018 versions ? 
Would appreciate a fast response :)

**Comment by AliSferea** [comment]
I managed to do it, in a not graceful way.
I'd created a new xcode project, and there I integrated Unity with the tutorial. Afterward I copy and paste all my project to this new created one, and now got it working.
