### ISSUE TITLE
Unity - Swift communication

### ISSUE THREAD

**Issue by physiord** [jiulongw/swift-unity#9]
Hello,

Would you/someone like to improve this awesome guide by adding an example how to call Swift functions FROM Unity?

Thanks again for this great template.

**Comment by physiord** [comment]
This was helpful:
https://github.com/miyabi/unity-swift

Only thing you need to change in the example code is 
    static func swiftMethod(_ message: String) {

to 
 @objc static func swiftMethod(_ message: String) {

**Comment by jplongo** [comment]
How did you generate the UnitySwift-Swift.h file ?
I'm trying it but this file is not created.
Issue referenced here : https://github.com/miyabi/unity-swift/issues/1

**Comment by jiulongw** [comment]
@jplongo 

There are two ways:

1. If you try to add .mm file to your Swift project via Xcode, Xcode will ask you if you want to create a bridging header file.  Simply click yes and done.

https://developer.apple.com/library/content/documentation/Swift/Conceptual/BuildingCocoaApps/MixandMatch.html

2. Create .h file by yourself with name of your choice, then add it to build settings.

![inkedscreen shot 2017-11-10 at 10 01 07 am_li](https://user-images.githubusercontent.com/1650734/32671979-52e99094-c5fe-11e7-9860-2cae0beb283a.jpg)

**Comment by jplongo** [comment]
I already have a bridge header, but my main problem is that I can't call AppDelegate.stopUnity() from `UnityUtils.mm`. 
If I include `MyProjectName-Swift.h` has seen in documentation, I issue weird build error. 

So I've used another way to call `stopUnity()` from `.mm` file by using NotificationCenter and adding an Observer.
Work really well, and now I can quit Unity and back to my native app 👍 

My app is now complete except for only one thing. GVR ! This SDK drive me crazy.

I can start Unity in nonVR mode, stop unity and back to my app.
I can start Unity, toggle from VR to non VR view. 
But after enabling VR, turning it off and back to my unity non VR view, If I click on my quit button,
`stopUnity()` is called, I return to my native view, but can't touch anything. It seems that GVR keep touch handler and even if unity is stopped, GVR keep it.
So now I loose my time trying to find how to solve this issue...

Thanks for your help
