### ISSUE TITLE
Unity 2018 support

### ISSUE THREAD

**Issue by rxmarcus** [jiulongw/swift-unity#92]
I realize that this doesn't claim to support Unity 2018 but am wondering if anyone knows how easy it would be to get this working with Unity 2018? 

The current error I get when attempting to build with Unity 2018.1.6f1 is something about the storyboard not containing a controller 'unitySplashStoryboard'.

`'NSInvalidArgumentException', reason: 'Storyboard (<UIStoryboard: 0x1c0a74180>) doesn't contain a view controller with identifier 'unitySplashStoryboard''`

this error comes from this method inside SplashScreen.mm:

`void ShowSplashScreen(UIWindow* window)
{
    bool hasStoryboard = [[NSBundle mainBundle] pathForResource: @"LaunchScreen" ofType: @"storyboardc"] != nullptr;

    if (hasStoryboard)
    {
        UIStoryboard *storyboard = [UIStoryboard storyboardWithName: @"LaunchScreen" bundle: [NSBundle mainBundle]];
        _controller = [storyboard instantiateViewControllerWithIdentifier: @"unitySplashStoryboard"];
    }
    else
        _controller = [[SplashScreenController alloc] init];

    [_controller create: window];
    [window makeKeyAndVisible];
}`

**Comment by jiulongw** [comment]
FYI https://github.com/jiulongw/swift-unity/pull/90

**Comment by rxmarcus** [comment]
Thank you!
