### ISSUE TITLE
App don't build on simulator 

### ISSUE THREAD

**Issue by HebaMohamed** [jiulongw/swift-unity#97]
Thank you so much for your efforts the project work on device but when working on simulator I get that error  in UnityAppController.mm:509:13: 

No matching function for call to 'objc_msgSend

<img width="1435" alt="screen shot 2018-08-09 at 10 45 10 pm" src="https://user-images.githubusercontent.com/14299338/43924835-e6baccf4-9c25-11e8-9a4a-622504864532.png">

I need your help guys and thanks in advance.

**Comment by jiulongw** [comment]
AFAIK Unity iPhone platform does not have x86_64 libs which means it cannot run in default simulator which is x86_64 based.

Things could have been changed but you can test if you can run Unity project in simulator without this plugin.
