### ISSUE TITLE
linker error when building a big project

### ISSUE THREAD

**Issue by eximarus** [jiulongw/swift-unity#99]
ld: b(l) ARM64 branch out of range (149168228 max is +/-128MB): from _unity_init (0x100005E80) to _objc_autoreleasePoolPop@0x00000000 (0x108E47F4C) in '_unity_init' from /Users/g4g/Library/Developer/Xcode/DerivedData/DemoApp-djiabxgtrnckglfbfrkmrqvthzrf/Build/Intermediates.noindex/DemoApp.build/Debug-iphoneos/DemoApp.build/Objects-normal/arm64/UnityUtils.o for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

at this point my project has to compile around 800 source files. building the normal way directly from the unity generated project works fine. im using unity 2018.2.0f

**Comment by InhaleExhale** [comment]
We're also having issues with this when trying to switch to the .NET 4.x Equivalent scripting runtime version. 

Building a reasonably large project for iOS using Unity 2018.2.16f and Xcode 10.1, I see the following in the linker log:

`ld: warning: arm64 function not 4-byte aligned: _unwind_tester from /Users/.../ios-dotnet4/Libraries/libiPhone-lib.a(unwind_test_arm64.o)
final section layout:
    __TEXT/__text addr=0x100004280, size=0x01CD8CBC, fileOffset=0x00004280, type=1
    __TEXT/.il2cpp addr=0x101CDCF3C, size=0x0AAB4750, fileOffset=0x01CDCF3C, type=1
    __TEXT/__stubs addr=0x10C79168C, size=0x00003D20, fileOffset=0x0C79168C, type=28
    __TEXT/__stub_helper addr=0x10C7953AC, size=0x00003AF8, fileOffset=0x0C7953AC, type=32
    __TEXT/__gcc_except_tab addr=0x10C798EA4, size=0x00B231B0, fileOffset=0x0C798EA4, type=0
    __TEXT/__cstring addr=0x10D2BC060, size=0x001D4712, fileOffset=0x0D2BC060, type=13
    __TEXT/__const addr=0x10D490780, size=0x01586FBF, fileOffset=0x0D490780, type=0
    __TEXT/__objc_methname addr=0x10EA1773F, size=0x00016254, fileOffset=0x0EA1773F, type=14
    __TEXT/__objc_classname addr=0x10EA2D993, size=0x0000155B, fileOffset=0x0EA2D993, type=14
    __TEXT/__objc_methtype addr=0x10EA2EEEE, size=0x00005E5F, fileOffset=0x0EA2EEEE, type=14
    __TEXT/__unwind_info addr=0x10EA34D50, size=0x0021EE74, fileOffset=0x0EA34D50, type=22
    __TEXT/__eh_frame addr=0x10EC53BC8, size=0x00000438, fileOffset=0x0EC53BC8, type=19
    __DATA/__got addr=0x10EC54000, size=0x00000B38, fileOffset=0x0EC54000, type=29
    __DATA/__la_symbol_ptr addr=0x10EC54B38, size=0x000028C0, fileOffset=0x0EC54B38, type=27
    __DATA/__mod_init_func addr=0x10EC573F8, size=0x000016D8, fileOffset=0x0EC573F8, type=33
    __DATA/__const addr=0x10EC58AD0, size=0x004E5198, fileOffset=0x0EC58AD0, type=0
    __DATA/__cfstring addr=0x10F13DC68, size=0x00011A00, fileOffset=0x0F13DC68, type=17
    __DATA/__objc_classlist addr=0x10F14F668, size=0x000005A8, fileOffset=0x0F14F668, type=0
    __DATA/__objc_nlclslist addr=0x10F14FC10, size=0x00000018, fileOffset=0x0F14FC10, type=0
    __DATA/__objc_catlist addr=0x10F14FC28, size=0x00000070, fileOffset=0x0F14FC28, type=24
    __DATA/__objc_nlcatlist addr=0x10F14FC98, size=0x00000018, fileOffset=0x0F14FC98, type=0
    __DATA/__objc_protolist addr=0x10F14FCB0, size=0x00000170, fileOffset=0x0F14FCB0, type=0
    __DATA/__objc_imageinfo addr=0x10F14FE20, size=0x00000008, fileOffset=0x0F14FE20, type=0
    __DATA/__objc_const addr=0x10F14FE28, size=0x000218B0, fileOffset=0x0F14FE28, type=0
    __DATA/__objc_selrefs addr=0x10F1716D8, size=0x00005848, fileOffset=0x0F1716D8, type=15
    __DATA/__objc_protorefs addr=0x10F176F20, size=0x00000040, fileOffset=0x0F176F20, type=0
    __DATA/__objc_classrefs addr=0x10F176F60, size=0x00000928, fileOffset=0x0F176F60, type=23
    __DATA/__objc_superrefs addr=0x10F177888, size=0x00000410, fileOffset=0x0F177888, type=0
    __DATA/__objc_ivar addr=0x10F177C98, size=0x000009DC, fileOffset=0x0F177C98, type=0
    __DATA/__objc_data addr=0x10F178678, size=0x00003890, fileOffset=0x0F178678, type=0
    __DATA/__data addr=0x10F17BF10, size=0x03F0EEE8, fileOffset=0x0F17BF10, type=0
    __DATA/__bss addr=0x11308AE00, size=0x000D0A38, fileOffset=0x00000000, type=25
    __DATA/__common addr=0x11315B840, size=0x002745BC, fileOffset=0x00000000, type=25
ld: b(l) ARM64 branch out of range (209246668 max is +/-128MB): from _main (0x100004280) to __Unwind_Resume@0x00000000 (0x10C791D64) in '_main' from /Users/.../Library/Developer/Xcode/DerivedData/Unity-iPhone-cqigewzpweggozeqtvochubyeymf/Build/Intermediates.noindex/Unity-iPhone.build/Debug-iphoneos/Unity-iPhone.build/Objects-normal/arm64/main.o for architecture arm64
`
